### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by MarianAldenhoevel** [zanders3/json#18]
Hi Alex,

Your JSON parser has saved my life. 

I found it just minutes before embarking on doing the same myself and I am positive it would not have come out as beautiful as yours.

I am working within the limits of a quite crappy application that supposedly is extendable using C# but fails that claim on many counts. So neither of the common solutions for digesting JSON worked for me and the only way forward is straight non-library literally-put-stuff-here coding. Which you provided.

Thank you very, very much!

Your code worked almost out of the box. I did have to change the Stack<List<string>> splitArrayPool to a List<List<string>>. I blame the general crappiness of the environment I am stuck in on that, because it simply refused to provide a Stack<T> no matter what I tried. And I feel sorry for the mutilation.

Have a good time!

**Comment by zanders3** [comment]
Glad it was useful!
