### ISSUE TITLE
Suitable license attribution

### ISSUE THREAD

**Issue by novabyte** [zanders3/json#22]
@zanders3 I wanted to check you're happy with the attribution of the library and your work in the library we just open-sourced. - https://github.com/heroiclabs/nakama-dotnet

The README suggest we add this library as sources to a project which requires it.

> Simply copy and paste the JSON Parser and/or the JSON Writer into your project. I also provide NuGet but I recommend the copy paste route ;)

That's what I've done but added it like so:

- The source files have an MIT header at the top of each of them.
- The folder with the sources has your MIT license file copied into it.
- A [note in the README](https://github.com/heroiclabs/nakama-dotnet#special-thanks) mentions this project.

Let me know if you want anything changed. Thanks for the great work. 👍

**Comment by zanders3** [comment]
That's great! Nice project.

**Comment by novabyte** [comment]
Perfect. Thanks @zanders3!
