### ISSUE TITLE
Unicode's backslash lost problem

### ISSUE THREAD

**Issue by imcheney** [zanders3/json#23]
When I tries to convert a json to a Dictionary<string, object>, my Chinese characters (e.g. "\u94b1\u4e0d\u591f!") inside dictionary values will become "u94b1u4e0du591f!", thus make it not readable any more.

**Comment by zanders3** [comment]
I couldn't reproduce the issue. I added those characters as a test case to the unit tests though and it passes:

https://github.com/zanders3/json/commit/6bf8bff4a7d4406f09666ddf460f70c4f9ae5d20
