### ISSUE TITLE
Can't parse DateTime? 

### ISSUE THREAD

**Issue by RefX32** [zanders3/json#30]
I am unable to parse this. Comes back as default DateTime.Min value. 

String:
`{"MachineID":"abc","LicenseKey":"def","AuthToken":"3926AB247AF62B3F750BE991963B887E37F1DD61","ExpirationDate":"01/01/2040","ServerValidationToken":"ghi","IsSuccess":true,"LicenseErrorMessage":null}`

Class:
```
    internal class MyClass
    {
        public string MachineID { get; set; }
        public string LicenseKey { get; set; }
        public string AuthToken { get; set; }
        public DateTime ExpirationDate { get; set; } // Issue is here.
        public string ServerValidationToken { get; set; }
        public bool IsSuccess { get; set; }
        public string LicenseErrorMessage { get; set; }
    }
```

**Comment by zanders3** [comment]
DateTime is not part of the formal JSON spec which is why this is not implemented - http://json.org/
You'll want to make that field as a string and fix it up afterwards, OR add some code to the parser to handle a DateTime property.

**Comment by RefX32** [comment]
Okay, I've passed it as string. "ExpirationDateString", and on the client parsed it back to DateTime format using DateTime.Parse(); Feel free to close this.
