### ISSUE TITLE
Lose Precision when parsing Int, long & float 

### ISSUE THREAD

**Issue by ParallxStudio** [zanders3/json#32]
Example : when parsing1577999999 it will give 1577800000

**Comment by zanders3** [comment]
Closing due to not enough info. Could you provide more information? e.g. a sample json file or ideally a c# test case.

**Comment by alsaleem00** [comment]
this is a bug. values greater than 2^31 are not parsed correctly. they are returned as 0
I found this bug in jasonparser.cs line 295/296.
I solved this by replacing int with long.
Should be considered in next release.
