### ISSUE TITLE
How is System.Threading.Tasks used in JSONWriter?

### ISSUE THREAD

**Issue by bitinn** [zanders3/json#5]
This library works in Unity, with the exception of `System.Threading.Tasks` namespace, which is .NET 4 (while Unity is 3.5-ish). I commented it out, and Unity doesn't complain anymore, so I am wondering how it's used.

PS: I only use JSONParser at the moment, so it isn't a big deal to me, just wondering.

**Comment by zanders3** [comment]
I wrote this parser specifically aimed at Unity - I should probably comment out that include! It minimises the amount of memory garbage generated and it doesn't use the JIT.

**Comment by zanders3** [comment]
I've removed that unused using - it should definitely compile for unity now.

**Comment by bitinn** [comment]
Thx, I have been using this module and it's great!

Seem particular suitable for:

- i18n file
- game state

In both cases you may want a simple anonymous object, and you don't need advanced parser because the data structure is very simple. I almost wrote my own before I found yours.

This is a lot more pleasant to use than Json.NET or other existing solutions that aims to be full feature serializer/deserializer.
