### ISSUE TITLE
empty list '[]' is parsed to a list with null

### ISSUE THREAD

**Issue by shooshx** [zanders3/json#7]
when calling JSONParser.ParseAnonymousValue() with the string "[]" it returns a list with 1 null element.
This is because JSONParser.Split() always adds at the end the string in the stringBuilder, even if it is an empty string

**Comment by zanders3** [comment]
That's a bug - it should be an empty list instead.

**Comment by Yanpas** [comment]
The bug cause is line 118:
`splitArray.Add(stringBuilder.ToString());`
