### ISSUE TITLE
Should this work on Windows 10 Core?

### ISSUE THREAD

**Issue by 1RedOne** [zanders3/json#9]
Hi, 

  I'm trying to write a Windows 10 Core app for my Raspberry Pi, and they shipped it with practically zero JSON Support.  I was thrilled when I found your class here, but when I try to add it, I see red squiggles in Visual Studio. 

`Error	CS1061	'Type' does not contain a definition for 'IsGenericType' and no extension method 'IsGenericType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	IoTCoreDefaultApp	C:\temp\Iot\IoTCoreDefaultApp\TinyJson.cs	169	Active`

`Error	CS1061	'Type' does not contain a definition for 'IsGenericType' and no extension method 'IsGenericType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	IoTCoreDefaultApp	C:\temp\Iot\IoTCoreDefaultApp\TinyJson.cs	182	Active
`

**Comment by zanders3** [comment]
Interesting. Looks like some features of .net are not supported. You could try commenting out the code that depends on that I guess? At the very least you should be able to parse anonymous structures i.e. .FromJson<object>();

**Comment by 1RedOne** [comment]
Turns out that .net Core offers a `Windows.Data.Json` namespace which has some *OK* JSON parsing skills.  Thanks for commenting, this can be closed.
